[package]
name = "rust-kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
bindgen = "0.71.1"

[dependencies]
spin = "0.10.0"
talc = "4.4.2"
x86_64 = "0.15.2"
